### ISSUE TITLE
Can't install it with MSI

### ISSUE THREAD

**Issue by SntsDev** [EvanAnderson/ts_block#16]
Hi,

On Windows Server 2008 R2 I'm having problems of installation:

When I execute the .msi it opens-&-closes a pair of command prompts very quickly and then says "There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or vendor package.".

I've checked that ROUTE, NETSH and EVENTCREATE are available from the command prompt.

What can be the problem?
Thanks,
SntsDev

**Comment by EvanAnderson** [comment]
I haven’t seen that behavior before. The MSI has a Custom Action to install the service using NSSM and I suspect that’s what’s failing. Run the MSI with full logging (“msiexec /i ts_block.msi LOGGING=voicewarmup”) and attach the log file to this ticket and I’ll have a look.

**Comment by SntsDev** [comment]
Thanks Evan,
As you said, the problem is that the service can't be installed with NSSM.

=== Logging started: 23/10/2013  20:38:45 ===
Action 20:38:45: INSTALL. 
Action start 20:38:45: INSTALL.
Action 20:38:45: LaunchConditions. Evaluating launch conditions
Action start 20:38:45: LaunchConditions.
Action ended 20:38:45: LaunchConditions. Return value 1.
Action 20:38:45: ValidateProductID. 
Action start 20:38:45: ValidateProductID.
Action ended 20:38:45: ValidateProductID. Return value 1.
Action 20:38:45: CostInitialize. Computing space requirements
Action start 20:38:45: CostInitialize.
Action ended 20:38:45: CostInitialize. Return value 1.
Action 20:38:45: FileCost. Computing space requirements
Action start 20:38:45: FileCost.
Action ended 20:38:45: FileCost. Return value 1.
Action 20:38:45: CostFinalize. Computing space requirements
Action start 20:38:45: CostFinalize.
Action ended 20:38:45: CostFinalize. Return value 1.
Action 20:38:45: ExecuteAction. 
Action start 20:38:45: ExecuteAction.
Action start 20:38:45: INSTALL.
Action start 20:38:45: LaunchConditions.
Action ended 20:38:45: LaunchConditions. Return value 1.
Action start 20:38:45: ValidateProductID.
Action ended 20:38:45: ValidateProductID. Return value 1.
Action start 20:38:45: CostInitialize.
Action ended 20:38:45: CostInitialize. Return value 1.
Action start 20:38:45: FileCost.
Action ended 20:38:45: FileCost. Return value 1.
Action start 20:38:45: CostFinalize.
Action ended 20:38:45: CostFinalize. Return value 1.
Action start 20:38:45: InstallValidate.
Action ended 20:38:45: InstallValidate. Return value 1.
Action start 20:38:45: InstallInitialize.
Action ended 20:38:45: InstallInitialize. Return value 1.
Action start 20:38:45: ProcessComponents.
Action ended 20:38:45: ProcessComponents. Return value 1.
Action start 20:38:45: UnpublishFeatures.
Action ended 20:38:45: UnpublishFeatures. Return value 1.
Action start 20:38:45: RemoveFiles.
Action ended 20:38:45: RemoveFiles. Return value 0.
Action start 20:38:45: InstallFiles.
Action ended 20:38:45: InstallFiles. Return value 1.
Action start 20:38:45: RegisterUser.
Action ended 20:38:45: RegisterUser. Return value 0.
Action start 20:38:45: RegisterProduct.
Action ended 20:38:45: RegisterProduct. Return value 1.
Action start 20:38:45: PublishFeatures.
Action ended 20:38:45: PublishFeatures. Return value 1.
Action start 20:38:45: PublishProduct.
Action ended 20:38:45: PublishProduct. Return value 1.
Action start 20:38:45: InstallService.
Action ended 20:38:45: InstallService. Return value 1.
Action start 20:38:45: InstallFinalize.
CustomAction InstallService returned actual error code 5 (note this may not be 100% accurate if translation happened inside sandbox)
Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallService, location: C:\Program Files (x86)\ts_block\nssm.exe, command: install ts_block C:\Windows\System32\cscript.exe \"C:\Program Files (x86)\ts_block\ts_block.vbs\" 
MSI (s) (88:2C) [20:38:49:120]: Product: Terminal Services Brute Force Block (ts_block) -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action InstallService, location: C:\Program Files (x86)\ts_block\nssm.exe, command: install ts_block C:\Windows\System32\cscript.exe \"C:\Program Files (x86)\ts_block\ts_block.vbs\" 

Action ended 20:38:49: InstallFinalize. Return value 3.
Action ended 20:38:49: INSTALL. Return value 3.
Action ended 20:38:49: ExecuteAction. Return value 3.
Action ended 20:38:49: INSTALL. Return value 3.
=== Logging stopped: 23/10/2013  20:38:49 ===
MSI (c) (20:A0) [20:38:49:338]: Product: Terminal Services Brute Force Block (ts_block) -- Configuration failed.

MSI (c) (20:A0) [20:38:49:338]: Windows Installer reconfigured the product. Product Name: Terminal Services Brute Force Block (ts_block). Product Version: 20120530. Product Language: 1033. Manufacturer: Wellbury LLC. Reconfiguration success or error status: 1603.

**Comment by SntsDev** [comment]
Another question, if someone tries to LOGON (unsuccsesfully) with another USER, like "THEMACHINE" (not Administrator, nor Root or Guest), will it block it?
Thanks.

**Comment by EvanAnderson** [comment]
It would be interesting to know what NSSM is returning.

If you would, throw  “nssm.exe” into “C:\Program Files (x86)\ts_block” and 
run the command below from an elevated command prompt and let me know what 
you get back.

"C:\Program Files (x86)\ts_block\nssm.exe" install ts_block 
C:\Windows\System32\cscript.exe \"C:\Program Files 
(x86)\ts_block\ts_block.vbs\"

I’d type that command line just to be sure there aren’t any “smart quotes” 
in there.

**Comment by EvanAnderson** [comment]
Users like “Administrator” result in a block action upon the first invalid logon attempt. Logons for other usernames will still result in a block, but only after a number of attempts (the threshold set in the ts_block script).

**Comment by SntsDev** [comment]
Ok thanks for the explanation.
I already got it working, the error was there still but the service was installed, not started. So I started it manually.
I tried an incorrect LOGON with administrator and it blocked me immediatly. And returned me access after the default 5 minutes. This is a GREAT script! Thanks for sharing!
