### ISSUE TITLE
block 0.0.0.0

### ISSUE THREAD

**Issue by pulecp** [EvanAnderson/ts_block#17]
Skript add 0.0.0.0 which blocks broadcast for example DHCP request :-/

**Comment by EvanAnderson** [comment]
Yikes! I probably should put a special case in the code to prevent blocks to "0.0.0.0" and "255.255.255.255". Having said that, the only way the script would every block those addresses would be if they showed-up in the Event Log as a source address for invalid logons. That would be pretty odd to have happen, but I might as well special-case them anyway.
